sudo: false

script: npm run test:all

language: node_js

node_js:
  - node
  - 6
  - 5
  - 4
  - 0.12
  - 0.10

cache:
  directories:
    - node_modules

install:
  - npm i -g npm@latest
  - npm install

after_success:
  - bash <(curl -s https://codecov.io/bash)
